// Generated by hardware_3d/scripts/mem_integrity_reference.py --emit-sv (do not edit).
localparam logic [127:0] MIT_K_ENC = 128'h57aca79b6742b91da3d6c3450e4b5486;
localparam logic [127:0] MIT_K_MAC = 128'hcc14676fe6df056e7da11e8ab3fb2678;
localparam logic [127:0] MIT_K_TREE = 128'h953c79b79800ed6a1a9ead6b90d2c913;
localparam logic [127:0] MIT_ROOT_INIT = 128'hda9f5bc2f6a2d0b25cad154482e76ddb;
localparam int MIT_NSCRIPT = 4;
localparam logic [3:0] MIT_SCRIPT_BLK [4] = '{4'd2, 4'd5, 4'd2, 4'd15};
localparam logic [127:0] MIT_SCRIPT_PT [4] = '{128'h00112233445566778899aabbccddeeff, 128'hdeadbeefcafebabe0123456789abcdef, 128'ha5a5a5a55a5a5a5a0f0f0f0ff0f0f0f0, 128'h6bc1bee22e409f96e93d7e117393172a};
localparam logic [127:0] MIT_SCRIPT_ROOT [4] = '{128'hc655a186c4aae6e3275583f832469cf0, 128'hbfd750100a4c6895522d1c55f8fbc111, 128'hbf26ccd04a17ae3fa72e525f5d97142c, 128'ha41af15ba3ab684188a5420b0eb868ea};
localparam logic [127:0] MIT_CT2 = 128'hdf70cc82587e50726324a5785483ec9f;
localparam logic [127:0] MIT_MAC2 = 128'h82ac83fbbf1f559b496f7898f443db7a;
