param(
    [string]$AsmFile = "programs\demo.asm",
    [string]$TextFile = "text.hex",
    [string]$DataFile = "data.hex",
    [string]$ImageFile = "demo.hex",
    [string]$ContractFile = "programs\demo.contract",
    [string]$PlainTextOut = "decrypted_text.hex",
    [string]$ResealedImageFile = "demo_after.hex",
    [uint32]$Epoch = 0,
    [switch]$SkipDecryptCompare,
    [switch]$MemorySelfTest,
    [switch]$SkipResealedSecondRun,
    [string]$Cxx = "g++"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Invoke-Step {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][scriptblock]$Command
    )

    Write-Host ""
    Write-Host "[STEP] $Name"

    & $Command

    if ($LASTEXITCODE -ne 0) {
        throw "Step failed: $Name (exit code $LASTEXITCODE)"
    }
}

function Assert-FileExists {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Required file not found: $Path"
    }
}

function Remove-IfExists {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (Test-Path -LiteralPath $Path) {
        Remove-Item -LiteralPath $Path -Force
    }
}

function New-PostRunContract {
    param(
        [Parameter(Mandatory = $true)][string]$SourceContract,
        [Parameter(Mandatory = $true)][string]$OutputContract
    )

    $lines = Get-Content -LiteralPath $SourceContract
    $found = $false
    $out = New-Object System.Collections.Generic.List[string]

    foreach ($line in $lines) {
        if ($line -match '^\s*signature\.pre_zero\s*=') {
            $out.Add("signature.pre_zero=false")
            $found = $true
        } else {
            $out.Add($line)
        }
    }

    if (-not $found) {
        $out.Add("")
        $out.Add("# Generated by run_pipeline.ps1 for re-running a post-execution resealed image.")
        $out.Add("signature.pre_zero=false")
    }

    Set-Content -LiteralPath $OutputContract -Value $out -Encoding ascii
}

Write-Host "============================================================"
Write-Host " Crypto3DStackCPU secure build / seal / execute pipeline"
Write-Host "============================================================"

Assert-FileExists $AsmFile
Assert-FileExists "src\3d.cpp"
Assert-FileExists "src\3d.h"
Assert-FileExists "src\header.h"
Assert-FileExists "src\asm_to_hex.cpp"
Assert-FileExists "src\encryptor.cpp"
Assert-FileExists "src\decryptor.cpp"
Assert-FileExists "src\3d_test.cpp"

if (-not [string]::IsNullOrWhiteSpace($ContractFile)) {
    Assert-FileExists $ContractFile
}

Remove-IfExists $TextFile
Remove-IfExists $DataFile
Remove-IfExists $ImageFile
Remove-IfExists $PlainTextOut
Remove-IfExists $ResealedImageFile
Remove-IfExists "postrun.contract"

# Desktop GCC/MinGW does not understand Vitis HLS pragmas.
# Keep them in the source for HLS, but suppress desktop compiler noise.
$CommonFlags = @(
    "-std=c++17",
    "-O2",
    "-Wall",
    "-Wextra",
    "-Wpedantic",
    "-Wno-unknown-pragmas"
)

Invoke-Step "Build custom assembler" {
    $args = @()
    $args += $CommonFlags
    $args += "src\asm_to_hex.cpp"
    $args += "-o"
    $args += "asm_to_hex.exe"
    & $Cxx @args
}

Invoke-Step "Assemble ASM -> text/data HEX" {
    & ".\asm_to_hex.exe" $AsmFile $TextFile $DataFile
}

Assert-FileExists $TextFile
Assert-FileExists $DataFile

Invoke-Step "Build encryptor" {
    $args = @()
    $args += $CommonFlags
    $args += "src\3d.cpp"
    $args += "src\encryptor.cpp"
    $args += "-o"
    $args += "encryptor_single.exe"

    # MinGW/GCC on Windows does not honor MSVC's:
    #   #pragma comment(lib, "bcrypt.lib")
    # BCryptGenRandom therefore needs explicit bcrypt linkage.
    if ($env:OS -eq "Windows_NT") {
        $args += "-lbcrypt"
    }

    & $Cxx @args
}

Invoke-Step "Build decryptor" {
    $args = @()
    $args += $CommonFlags
    $args += "src\3d.cpp"
    $args += "src\decryptor.cpp"
    $args += "-o"
    $args += "decryptor_single.exe"
    & $Cxx @args
}

Invoke-Step "Build CPU execution testbench" {
    $args = @()
    $args += $CommonFlags
    $args += "src\3d.cpp"
    $args += "src\3d_test.cpp"
    $args += "-o"
    $args += "3d_test_single.exe"
    & $Cxx @args
}

if ($Epoch -eq 0) {
    Invoke-Step "Seal encrypted/authenticated image" {
        & ".\encryptor_single.exe" $TextFile $DataFile $ImageFile
    }
} else {
    Invoke-Step "Seal encrypted/authenticated image with explicit epoch" {
        & ".\encryptor_single.exe" $TextFile $DataFile $ImageFile $Epoch
    }
}

Assert-FileExists $ImageFile

if (-not $SkipDecryptCompare) {
    Invoke-Step "Validate image and decrypt .text for assembler comparison" {
        & ".\decryptor_single.exe" $ImageFile $TextFile $PlainTextOut
    }

    Assert-FileExists $PlainTextOut
}

$TestArgs = @($ImageFile)
if (-not [string]::IsNullOrWhiteSpace($ContractFile)) {
    $TestArgs += $ContractFile
}
$TestArgs += "--write-output"
$TestArgs += $ResealedImageFile

if ($MemorySelfTest) {
    $TestArgs += "--memory-self-test"
}

Invoke-Step "Execute CPU, verify contract, and validate resealed output" {
    & ".\3d_test_single.exe" @TestArgs
}

Assert-FileExists $ResealedImageFile

if (-not $SkipResealedSecondRun) {
    # The first CPU run already validates that the output image can be reloaded.
    # This optional second run executes the post-run image again. Its signature
    # word is expected to be non-zero before execution, so use a temporary
    # contract with signature.pre_zero disabled.
    if (-not [string]::IsNullOrWhiteSpace($ContractFile)) {
        New-PostRunContract -SourceContract $ContractFile -OutputContract "postrun.contract"

        Invoke-Step "Second execution of resealed output image" {
            & ".\3d_test_single.exe" $ResealedImageFile "postrun.contract"
        }
    } else {
        Invoke-Step "Second execution of resealed output image" {
            & ".\3d_test_single.exe" $ResealedImageFile
        }
    }
}

Write-Host ""
Write-Host "============================================================"
Write-Host "[ALL TESTS PASSED]"
Write-Host "ASM:       $AsmFile"
Write-Host "Text HEX:  $TextFile"
Write-Host "Data HEX:  $DataFile"
Write-Host "Image:     $ImageFile"
Write-Host "Resealed:  $ResealedImageFile"
Write-Host "============================================================"

