#!/usr/bin/env python3
"""Independent Python reference model of the Vertical Trust Fabric protocol.

Uses the `cryptography` package (AES, AES-CMAC per NIST SP 800-38B), not the
repository's own AES, so it is an independent check of both the C++ model
(src/vertical_trust_fabric.h) and the RTL (hardware_3d/rtl/*).

  python hardware_3d/scripts/vtf_reference.py --self-test
  python hardware_3d/scripts/vtf_reference.py --emit-sv hardware_3d/tb/vtf_vectors.svh

Message layout (32 bytes, big-endian words), identical to serializeRequest /
serializeResponse in the C++ model:
  req: C3 D1 requester op layer 00 00 00 | addr | data | seq | epoch | nonce | "VTF1"
  rsp: C3 D2 requester op layer status 00 00 | addr | data | seq | epoch | nonce | "VTF2"
"""
from __future__ import annotations

import argparse
import struct
import sys

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.cmac import CMAC

REQ_DOMAIN = bytes.fromhex("56544652455155455354 4B3100000001".replace(" ", ""))
RSP_DOMAIN = bytes.fromhex("565446524553504F4E53454B00000001")
TEST_ROOT = bytes.fromhex("2B7E151628AED2A6ABF7158809CF4F3C")  # simulation root of the C++ model
REQUESTERS = 5


def aes(key: bytes, block: bytes) -> bytes:
    enc = Cipher(algorithms.AES(key), modes.ECB()).encryptor()
    return enc.update(block) + enc.finalize()


def cmac(key: bytes, msg: bytes) -> bytes:
    c = CMAC(algorithms.AES(key))
    c.update(msg)
    return c.finalize()


def base_keys(root: bytes) -> tuple[bytes, bytes]:
    return aes(root, REQ_DOMAIN), aes(root, RSP_DOMAIN)


def epoch_keys(root: bytes, epoch: int) -> tuple[list[bytes], bytes]:
    kreq, krsp = base_keys(root)
    req = [aes(kreq, b"VTFE" + struct.pack(">II", epoch, r) + b"KDF1") for r in range(REQUESTERS)]
    rsp = aes(krsp, b"VTFE" + struct.pack(">I", epoch) + b"RSP0" + b"KDF1")
    return req, rsp


def route_nonce(requester: int, seq: int, layer: int, epoch: int) -> int:
    m = 0xFFFFFFFF
    x = 0xC3D5A17E ^ ((requester * 0x9E3779B9) & m)
    x ^= (seq * 0x85EBCA6B) & m
    x ^= (layer * 0xC2B2AE35) & m
    x ^= (epoch * 0x27D4EB2D) & m
    x ^= x >> 16
    x = (x * 0x7FEB352D) & m
    x ^= x >> 15
    x = (x * 0x846CA68B) & m
    x ^= x >> 16
    return x


def request_msg(requester, op, layer, addr, data, seq, epoch, nonce) -> bytes:
    return (bytes([0xC3, 0xD1, requester, op, layer, 0, 0, 0])
            + struct.pack(">IIIII", addr, data, seq, epoch, nonce) + b"VTF1")


def response_msg(requester, op, layer, status, addr, data, seq, epoch, nonce) -> bytes:
    return (bytes([0xC3, 0xD2, requester, op, layer, status, 0, 0])
            + struct.pack(">IIIII", addr, data, seq, epoch, nonce) + b"VTF2")


def self_test() -> None:
    # vectors shared with src/vtf_hls_tb.cpp and hardware_3d/tb/tb_aes_cmac32.sv
    assert cmac(bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c"),
                bytes.fromhex("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e51")).hex() \
        == "ce0cbf1738f4df6428b1d93bf12081c9"
    assert cmac(bytes(16), bytes(32)).hex() == "3437d43a23ac3ce2025ceaf9c237ab53"
    assert aes(bytes.fromhex("000102030405060708090a0b0c0d0e0f"),
               bytes.fromhex("00112233445566778899aabbccddeeff")).hex() == "69c4e0d86a7b0430d8cdb78070b4c55a"
    print("reference self-test passed")


def sv_hex(b: bytes) -> str:
    return f"{len(b) * 8}'h{b.hex()}"


def emit_sv(path: str) -> None:
    """Golden values for tb_vtf_system: keys for the test root and two epochs, and tags
    for the scripted transactions of the system testbench."""
    kreq, krsp = base_keys(TEST_ROOT)
    lines = ["// Generated by hardware_3d/scripts/vtf_reference.py --emit-sv (do not edit).",
             f"localparam logic [127:0] VEC_ROOT = {sv_hex(TEST_ROOT)};",
             f"localparam logic [127:0] VEC_BASE_REQ = {sv_hex(kreq)};",
             f"localparam logic [127:0] VEC_BASE_RSP = {sv_hex(krsp)};"]
    for e in (1, 2):
        req, rsp = epoch_keys(TEST_ROOT, e)
        for r in range(REQUESTERS):
            lines.append(f"localparam logic [127:0] VEC_E{e}_REQ{r} = {sv_hex(req[r])};")
        lines.append(f"localparam logic [127:0] VEC_E{e}_RSP = {sv_hex(rsp)};")
    # one fully specified request/response pair (security tier write, epoch 1)
    msg = request_msg(2, 1, 2, 0x10, 0xA5A55A5A, 1, 1, route_nonce(2, 1, 2, 1))
    req1, rsp1 = epoch_keys(TEST_ROOT, 1)
    lines.append(f"localparam logic [255:0] VEC_REQ_MSG = {sv_hex(msg)};")
    lines.append(f"localparam logic [127:0] VEC_REQ_TAG = {sv_hex(cmac(req1[2], msg))};")
    rmsg = response_msg(2, 1, 2, 1, 0x10, 0xA5A55A5A, 1, 1, route_nonce(2, 1, 2, 1))
    lines.append(f"localparam logic [255:0] VEC_RSP_MSG = {sv_hex(rmsg)};")
    lines.append(f"localparam logic [127:0] VEC_RSP_TAG = {sv_hex(cmac(rsp1, rmsg))};")
    lines.append(f"localparam logic [31:0]  VEC_NONCE_2_1_2_1 = 32'h{route_nonce(2, 1, 2, 1):08x};")
    open(path, "w", newline="\n").write("\n".join(lines) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--emit-sv")
    a = ap.parse_args()
    self_test()
    if a.emit_sv:
        emit_sv(a.emit_sv)
    sys.exit(0)
