// Generated by hardware_3d/scripts/mem_integrity_reference.py --emit-cpp (do not edit).
#pragma once
#include <cstdint>
namespace mit_vectors {
static const uint32_t ROOT_INIT[4] = {0xda9f5bc2u,0xf6a2d0b2u,0x5cad1544u,0x82e76ddbu};
static const unsigned SCRIPT_BLK[4] = {2, 5, 2, 15};
static const uint32_t SCRIPT_PT[4][4] = {{0x00112233u,0x44556677u,0x8899aabbu,0xccddeeffu}, {0xdeadbeefu,0xcafebabeu,0x01234567u,0x89abcdefu}, {0xa5a5a5a5u,0x5a5a5a5au,0x0f0f0f0fu,0xf0f0f0f0u}, {0x6bc1bee2u,0x2e409f96u,0xe93d7e11u,0x7393172au}};
static const uint32_t SCRIPT_ROOT[4][4] = {{0xc655a186u,0xc4aae6e3u,0x275583f8u,0x32469cf0u}, {0xbfd75010u,0x0a4c6895u,0x522d1c55u,0xf8fbc111u}, {0xbf26ccd0u,0x4a17ae3fu,0xa72e525fu,0x5d97142cu}, {0xa41af15bu,0xa3ab6841u,0x88a5420bu,0x0eb868eau}};
static const uint32_t CT2[4] = {0xdf70cc82u,0x587e5072u,0x6324a578u,0x5483ec9fu};
static const uint32_t MAC2[4] = {0x82ac83fbu,0xbf1f559bu,0x496f7898u,0xf443db7au};
}  // namespace mit_vectors
